import './css/style.css'

import { Inter } from 'next/font/google'
import AppProvider from './app-provider'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${inter.variable}`}>
      <body className="font-inter antialiased bg-gray-100 text-gray-600">
        <AppProvider>
          {children}
        </AppProvider>
      </body>
    </html>
  )
}
